
spring.application.name=oficio
spring.datasource.url=jdbc:mysql://root:sBFwDZobfrJJYiwsnnDTZbeRtiyTgVIS@acela.proxy.rlwy.net:48316/railway
spring.datasource.username=root
spring.datasource.password=sBFwDZobfrJJYiwsnnDTZbeRtiyTgVIS

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
logging.level.org.springframework.security=DEBUG

jwt.secret=GVzdFNlY3JldEtleVBhcmFKV1RRdWVUaWVuZU11Y2hvc0NhcmFjdGVyZXNQYXJhU2VyU2VndXJh

